#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import Image

from acrv_ros_wrappers.srv import RefineNet

_pub = None
_service = None


def callback(msg):
    resp = _service(RefineNet._request_class(rgb_image=msg))
    _pub.publish(resp.segmented_image)


if __name__ == "__main__":
    rospy.init_node('debug')

    _service = rospy.ServiceProxy('/refinenet', RefineNet)
    _pub = rospy.Publisher('/debug', Image, queue_size=1)
    rospy.Subscriber('/camera/color/image_raw', Image, callback)

    rospy.spin()
